spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: ilya
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # (create, update, validate, none)
    show-sql: true  # Показывать SQL-запросы в логах
    open-in-view: false